{% set name = "granian" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/granian-{{ version }}.tar.gz
  sha256: ba7fbc76e9845dee40c7f8b28925db5b3324ff9bc17b76111b699a1642e21ce7

build:
  skip: true  # [py<38]
  entry_points:
    - granian = granian:cli.cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - maturin >=1.1.0,<1.5.0
    - pip
  run:
    - python
    - watchfiles >=0.21,<1.dev0
    - typer >=0.4.2
    - uvloop >=0.18.0,<0.19.dev0  # [not win]

    # For OSX rust
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  imports:
    - granian
  commands:
    - pip check
    - granian --help
  requires:
    - pip

about:
  home: https://github.com/emmett-framework/granian
  summary: A Rust HTTP server for Python applications
  dev_url: https://github.com/emmett-framework/granian
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
